use new web service

diff --git a/profile.lwprof/-ra b/profile.lwprof/-ra
--- a/profile.lwprof/-ra
+++ b/profile.lwprof/-ra
@@ -98,56 +98,77 @@
   #local pw=$(pw "$pwkey")
   local pw=$(_esh_y _ra_get_ldap_pw | openssl enc -d -a -A)
   [ -z "$pw" ] && {
-    echo "Could not retrieve password for \"$RA_USER\" to launch remoteadmin" >&2
+    echo "$FUNCNAME: could not retrieve password for \"$RA_USER\" to launch remoteadmin" >&2
     return 1
   }
-  local vmjson auth=$(printf "%s:%s" "$RA_USER" "$pw" | openssl enc -a -A)
+  local raw agents auth=$(printf "%s:%s" "$RA_USER" "$pw" | openssl enc -a -A)
   local auth_hdr=$(printf "Authorization: Basic %s" $auth)
   local endpoint=$RA_SERVER_BASE_URL/ra-get-agents
-  vmjson=$(curl -k -S -s -f -H "$auth_hdr" -H "X-Ra-Agent-Id: remoteadmin.private/127.0.0.1" $endpoint)
-  local rc=$?
-  if [ $rc -gt 0 ]; then
-    echo "Failed to read $endpoint"
+  if ! raw=$(curl -k -S -s -f -H "Accept: text/plain" -H "$auth_hdr" -H "X-Ra-Agent-Id: remoteadmin.private/127.0.0.1" $endpoint); then
+    echo "$FUNCNAME: failed to read $endpoint" >&2
     return 1
   fi
-  #local matching_indices=$(jq -c "[.[] | .hostname | test(\".*$filter.*\";\"i\")] | indices(true)" <<<$vmjson)
-  local matching=$(node - "$vmjson" "$filter" << 'EOF'
-var agents=JSON.parse(process.argv[2]);
-var filter=new RegExp(process.argv[3],"i");
-agents.map(function(agent,idx) {
-  if (agent.raHostname.search(filter)>=0) {
-    var ts=new Date(agent.createTimestamp).toLocaleString();
-    console.log("hostname=%s ip=%s ssh_port=%s back_port=%s create_ts='%s'",
-      agent.raHostname,agent.remoteAddress,
-      agent.raSshPort,agent.raBackPort,ts);
+  IFS=$'\n' read -d '' -a agents <<< "$raw"
+
+  local matching=() header=() raAgentIdIdx agent=()
+  IFS='|' read -a header <<< "${agents[0]}"
+
+  get_header_idx() {
+    local i
+    for ((i=0;i<${#header[@]};i++)); do
+      if [ ${header[$i]} = $1 ]; then
+        echo $i
+        return
+      fi
+    done
+    return 1
   }
-});
-EOF
-)
 
-  if [ ! "$matching" ]; then
-    echo "no matches for filter: $filter"
+  if ! raAgentIdIdx=$(get_header_idx raAgentId); then
+    echo "$FUNCNAME: failed to get raAgentIdIdx" >&2
     return 1
   fi
 
-  get_vm_data() {
-    local key=$1
-    local l
-    echo "$matching" | while read l; do
-      eval "$l"
-      echo "'${!key}'"
+  for ((i=1;i<${#agents[@]};i++)); do
+    agent=(${agents[$i]})
+    raAgentId=${agent[$raAgentIdIdx]}
+    if [[ $raAgentId =~ $filter ]]; then
+      matching+=("${agents[$i]}")
+    fi
+  done
+
+  if [ ${#matching[@]} -eq 0 ]; then
+    echo "$FUNCNAME: no matches for filter: $filter" >&2
+    return 1
+  fi
+
+  get_data() {
+    local i j data
+    IFS='|' read -a data <<< "${matching[$1]}"
+    for ((j=0;j<${#header[@]};j++)); do
+      printf "%s=%s;" ${header[$j]} "${data[$j]}"
     done
   }
 
-  local hostnames ips create_ts ssh_ports back_ports
-  eval hostnames=($(get_vm_data hostname)) choice=0
-  eval ips=($(get_vm_data ip))
-  eval create_ts=($(get_vm_data create_ts))
-  local n=$((${#hostnames[@]}-1))
+  fmt_date() {
+    epoch_seconds=$1 os=$(uname -s) fmt="%m/%d %H:%M:%S"
+    case $os in
+      Darwin|OpenBSD)
+        date -r $epoch_seconds +"$fmt"
+        ;;
+      Linux)
+        date --date=@$epoch_seconds +"$fmt"
+        ;;
+    esac
+  }
+
+  local n=$((${#matching[@]}-1)) choice=0
   if [ $n -ge 1 ]; then
     local choice_list=$(
-      for ((i=0; i<=$n; i++)); do
-        printf "%s/%s (%s)\n" ${hostnames[$i]} ${ips[$i]} "${create_ts[$i]}"
+      for ((i=0;i<=$n;i++)); do
+        eval "$(get_data $i)"
+        dt=$(fmt_date $createTimestamp)
+        printf "%s (%s)\n" $raAgentId "$dt"
       done
     )
     choice=$(-pick-something "Pick:" "$choice_list" 1) || {
@@ -155,52 +176,17 @@ EOF
       return 1
     }
   fi
-  eval ssh_ports=($(get_vm_data ssh_port))
-  local ssh_port=${ssh_ports[$choice]}
-  local hostname=${hostnames[$choice]}
-  eval back_ports=($(get_vm_data back_port))
-  local back_port=${back_ports[$choice]}
+
+  eval "$(get_data $choice)"
+
   local ip=${ips[$choice]}
-  local extra_params="$(get_extra_ssh_params $hostname)"
+  local extra_params="$(get_extra_ssh_params $raHostname)"
   if [ -n "$extra_params" ]; then
     echo "Passing extra params to ssh: $extra_params"
   fi
 
-  #chroot_dir=/var/remoteadmin-chroot/443
-  #ssh_config=/home/remoteadmin/ssh-files/ra-agent-ssh-config-$ssh_port
-  #cp_file=/home/remoteadmin/ssh-files/ra-agent-controlpath-$ssh_port
-
-  #SSH_STY_LBL=$hostname ssh -t -oProxyCommand="env ssh ra.lincware.com sudo chroot -u remoteadmin $chroot_dir ssh -v -F $ssh_config %r@127.0.0.1" $extra_params lincdoc@ra.lincware.com
-  #SSH_STY_LBL=$hostname ssh -t -oProxyCommand="env ssh ra.lincware.com sudo chroot -u remoteadmin $chroot_dir ssh -F $ssh_config -v %r@127.0.0.1 sudo sshd -i" $extra_params lincdoc@unknown
-  #SSH_STY_LBL=$hostname ssh -t ra.lincware.com sudo chroot -u remoteadmin $chroot_dir ssh -F $ssh_config -v lincdoc@127.0.0.1
-  #SSH_STY_LBL=$hostname ssh -vv -t -oProxyCommand="env ssh ra.lincware.com sudo chroot -u remoteadmin $chroot_dir ssh -F $ssh_config %r@127.0.0.1 sudo remoteadmin-lincdoc-sshd" $extra_params lincdoc@unknown
-  #SSH_STY_LBL=$hostname ssh -t -oProxyCommand="env ssh -A remoteadmin@ra.lincware.com ssh -F $ssh_config 127.0.0.1 bash -c \"':;. .remoteadmin-shell-functions && exec sudo sshd -i'\"" $extra_params lincdoc@unknown
-
-
-  my_init() {
-    local a=() c=() i
-    # RA_READ_PTY_FUNC is picked up by remoteadmin's _ra_read_pty function, we
-    # want to override it with _esh_y
-    export RA_READ_PTY_FUNC=_esh_y
-    if c=($(curl -f -s -S -H "$1" -H "Content-Type: application/json" http://127.0.0.1:$2/ra-get-shell-ctx/$3/$4)); then
-      for ((i=0;i<${#c[@]};i++)); do
-        a+=("$(echo ${c[$i]} | openssl enc -d -a -A)")
-      done
-      # needed -i arg with bash in order to pass along desired PS1 value
-      #a=(exec bash --norc --noprofile -i -c "${a[@]:7}" exec bash --norc --noprofile)
-      eval exec "${c[@]}" exec bash <>$SSH_TTY
-    fi
-  }
-
-
-  # create ESH_BASH_INIT (picked up by _init_ctx) with bound parameters to my_init
-  #eval "ESH_BASH_INIT() { $(declare -f my_init); my_init '$auth_hdr' $back_port $hostname $ip; }"
-
-  #SSH_STY_LBL=$hostname ssh -t -oProxyJump=remoteadmin@$RA_SSH_PROXY_JUMP_HOST -p $ssh_port $extra_params "$@" $RA_SSH_USER@127.0.0.1
-  #unset -f ESH_BASH_INIT
-
   local c=()
-  if c=($(curl -k -f -s -S -H "$auth_hdr" -H "Content-Type: application/json" -H "X-Ra-Agent-Id: $hostname/$ip" $RA_SERVER_BASE_URL/ra-get-shell-ctx)); then
-    SSH_STY_LBL=$hostname ssh -t -oProxyJump=remoteadmin@$RA_SSH_PROXY_JUMP_HOST -p $ssh_port $extra_params "$@" $RA_SSH_USER@127.0.0.1 "${c[@]}" exec bash
+  if c=($(curl -k -f -s -S -H "$auth_hdr" -H "Content-Type: application/json" -H "X-Ra-Agent-Id: $raAgentId" $RA_SERVER_BASE_URL/ra-get-shell-ctx)); then
+    SSH_STY_LBL=$hostname ssh -t -oProxyJump=remoteadmin@$RA_SSH_PROXY_JUMP_HOST -p $raSshPort $extra_params "$@" $RA_SSH_USER@127.0.0.1 "${c[@]}" exec bash
   fi
 }
