rework vim to work with crontab -e on openbsd, and hopefully be more robust in general

diff --git a/profile.lwprof/vim b/profile.lwprof/vim
--- a/profile.lwprof/vim
+++ b/profile.lwprof/vim
@@ -1,7 +1,6 @@
 # vim:filetype=sh
 vim() {
-  local VIMINIT VIM_CB exec=vim shell=bash sharg="$(bash --help|grep -- --import-functions)"
-  [ "$sharg" ] && shell="$shell $sharg"
+  local VIMINIT VIM_CB exec=vim shfile=$ESH_TMP/$USER.vimshell.$RANDOM
   if [ "$1" = "-visudo" ]; then
     local VISUAL=vim
     exec=visudo
@@ -11,24 +10,34 @@ vim() {
     exec=crontab
     shift
   fi
-  export VIM_CB=$ESH_TMP/$USER.vim.clipboard
-  touch $VIM_CB
-  chmod 600 $VIM_CB || {
-    echo "WARNING: could not chmod on $VIM_CB!"
-    return
-  }
-  export VIMINIT='map <c-v> :let @"=system("_esh_b zGetCb")<cr>:if col("$")-col(".")==1<bar>call feedkeys("p")<bar>else<bar>call feedkeys("P")<bar>endif<bar>redraw<bar>echon "Pasted " len(@") " characters"<cr>|vnoremap <C-c> y:call writefile(split(@","\n","b"),$VIM_CB)<cr>:!cp2cb $VIM_CB<cr>|colorscheme elflord|syntax enable|set cursorline noswapfile number hlsearch incsearch sw=2 ignorecase wrap nocompatible ruler ai showmatch modeline modelines=5 nobackup nowritebackup textwidth=0 expandtab formatoptions=croql wildignore=*.class path=.,,** shcf=""|autocmd Filetype java setlocal omnifunc=javacomplete#Complete'
 
-  vimshell() {
-    eval $(_esh_e)
-    eval "${BASH_ARGV[@]}"
-  }
-  export -f vimshell
+  export VIMINIT='map <c-v> :let @"=system("_esh_b zGetCb")<cr>:if col("$")-col(".")==1<bar>call feedkeys("p")<bar>else<bar>call feedkeys("P")<bar>endif<bar>redraw<bar>echon "Pasted " len(@") " characters"<cr>|vnoremap <C-c> y:call system("cp2cb",split(@","\n","b"))<cr>:echon "Copied " len(@") " characters"<cr>|colorscheme elflord|syntax enable|set cursorline noswapfile number hlsearch incsearch sw=2 ignorecase wrap nocompatible ruler ai showmatch modeline modelines=5 nobackup nowritebackup textwidth=0 expandtab formatoptions=croql wildignore=*.class path=.,,**|autocmd Filetype java setlocal omnifunc=javacomplete#Complete'
 
-  # NOTE: the space after vimshell was required for bash 4.3 on ARM ... not
-  # sure why ... but without it, running a shell command inside vim would fail,
-  # e.g. something like this:
-  #   :!pwd
-  # would not work. Strangely on bash 3.2 OSX it did not need the space
-  env SHELL="$shell -c vimshell " $exec "$@"
+  # create a shell script for vim system calls/subshells so that clipboard
+  # functions properly, even when editing crontabs
+  #
+  # NOTE: bash_init_string does similar things, might need to keep logic
+  # between these 2 similar
+
+  [ -e $shfile ] && { 
+    rm -f $shfile || {
+      echo "vim: could not remove $shfile"
+      return 1
+    }
+  }
+
+  {
+    echo "#!/usr/bin/env bash"
+    declare -p $(compgen -v ESH_)
+    _esh_e
+    declare -f _esh_e _esh_b _esh_l _esh_i
+    # unset SSH_CLIENT so that _esh_i does not delete ESH_STY file, see _esh_i
+    # for more detail
+    echo "SSH_CLIENT='' _esh_i $ESH_STY ESH_PORT </dev/null"
+    echo 'exec bash --norc --noprofile "$@"'
+  } > $shfile
+  chmod 700 $shfile
+
+  env SHELL=$shfile $exec "$@"
+  rm $shfile
 }
