continue

diff --git a/esh-init b/esh-init
--- a/esh-init
+++ b/esh-init
@@ -80,10 +80,10 @@ export -f _esh_e
 _esh_b() {
   local auth_token=${ESH_TERM_AUTH_TOKEN:-${ESH_AT:-no_token}}
   eval "$(_esh_e)"
-if [ -z "$auth_token" ]; then
-  echo missing: auth_token "${FUNCNAME[*]}" >&2
-  return 1
-fi
+  if [ -z "$auth_token" ]; then
+    echo "missing auth_token: stack trace: ${FUNCNAME[*]}" >&2
+    return 1
+  fi
   {
     read one_time_auth_token
     echo $one_time_auth_token
@@ -163,13 +163,13 @@ export -f _esh_l
 
 # shell init script here
 _esh_i() {
+echo "INSIDE $FUNCNAME:$ESH_TERM_AUTH_TOKEN-->$@" >&2
   local i=$HOME/.escreen_profile
   [ -f $i ] && . $i
   local t=$ESH_TMP u=$ESH_USER f=$(_esh_e -f)
   [ ! -d $t ] && mkdir $t && chmod 1777 $t
   [ ! -f $f ] && {
     _esh_e "$@"
-    #nohup sh -c "while kill -0 $$; do sleep 5; done; rm -f $f" </dev/null >/dev/null 2>&1 &
   }
   #[ $# -gt 0 ] && _esh_e "$@"
   # p0, p1, p2 are set by fpw call
@@ -195,7 +195,6 @@ _esh_i() {
   export -f _esh_e _esh_i _esh_b _esh_l _esh_y
   export PROMPT_COMMAND='-prompt'
   export -n ESH_AT ESH_TERM_AUTH_TOKEN
-echo $FUNCNAME exit: $ESH_AT >&2
 }
 
 export -f _esh_i
@@ -300,15 +299,10 @@ ESH_CORE=$ESH_HOME/core
 # unique ID to properly track the communications port (ESH_PORT) to use in a
 # given shell between various combinations of screen, sudo, and ssh
 export ESH_STY=$$
+export ESH_TERM_PID=$$
 
 if [ $# -gt 0 ]; then
-  f=$(mktemp)
-  {
-    echo ESH_TERM_AUTH_TOKEN=$1
-    echo 'export ESH_TERM_PID=$$'
-    echo "echo SOURCED $f"
-    echo '_esh_i $ESH_STY ESH_PORT'
-    echo "rm $f"
-  } >> $f
-  exec bash --init-file $f -i
+  ESH_TERM_AUTH_TOKEN=$1 _esh_i $ESH_STY ESH_PORT
+  e=$(ESH_TERM_AUTH_TOKEN=$1 _init_ctx -d $ESH_STY $ESH_PORT)
+  eval "$e"
 fi
