Fix VIM_CLIPBOARD.

diff --git a/expect-ssh b/expect-ssh
--- a/expect-ssh
+++ b/expect-ssh
@@ -152,6 +152,13 @@ proc load_mybashprefs {SSH_EXPECT} {
   append mybashprefs "export LOAD_MYBASHPREFS_MARKER='" $LOAD_MYBASHPREFS_MARKER "'\n"
   append mybashprefs {
 unset PROMPT_COMMAND
+export VIM_CLIPBOARD=/tmp/vim.clipboard.$USER
+touch $VIM_CLIPBOARD
+chmod 600 $VIM_CLIPBOARD || {
+  echo "WARNING: could not chmod on $VIM_CLIPBOARD, halting."
+  return
+}
+
 export VIMINIT='map <c-v> :echon "%paste_from_clipboard_in_vim"<cr>|vnoremap <C-c> y:call writefile(split(@","\n","b"),$VIM_CLIPBOARD)<cr>:!copy_to_clipboard $VIM_CLIPBOARD<cr>|colorscheme elflord|syntax enable|set noswapfile number hlsearch incsearch sw=2 ignorecase wrap nocompatible ruler ai showmatch modeline modelines=5 nobackup nowritebackup textwidth=0 expandtab formatoptions=croql wildignore=*.class path=.,,**|autocmd Filetype java setlocal omnifunc=javacomplete#Complete'
 export EDITOR=/usr/bin/vim
 export FCEDIT=$EDITOR
@@ -274,14 +281,6 @@ function rgrep() {
   find . -type f ! -wholename './build/*' ! -wholename '*/.svn*' ! -wholename '*.class' ! -wholename '*.jar' ! -wholename '*.swp' | xargs grep "$@" 2>/dev/null
 }
 export -f rgrep
-
-function vim() {
-  export VIM_CLIPBOARD=/tmp/vim.clipboard.$USER
-  touch $VIM_CLIPBOARD
-  chmod 600 $VIM_CLIPBOARD
-  /usr/bin/vim "$@"
-}
-export -f vim
 
 function tomcatlog() {
   local OPTS=$(getopt -o 23ecx -- "$@")
