Interim.

diff --git a/core/_ES_bootstrap b/core/_ES_bootstrap
--- a/core/_ES_bootstrap
+++ b/core/_ES_bootstrap
@@ -2,21 +2,8 @@
 #
 # _ES_bootstrap bootstraps a function
 #
-function _ES_bootstrap() {
+_ES_bootstrap() {
   local f=$1
-  local funcname=${funcfile/*.}
-  local s l fname pw script
-  if [ -f $f ]; then
-    if s="$(_esh_pw $funcname | openssl enc -d -a -aes256 -in $f -pass stdin | gzip -d -c)"; then
-      eval "$s" && _ES_set_loaded $funcname && "$@"
-      return
-    fi
-    # fall through to below, re-upload and cache the script
-  fi
-  [ ! -f $f ] && touch $f && chmod 666 $f
-  # cache the function
-  _ES_send_marker "$upmarker" $funcname > $f
-  # call ourself again, this time it should decrypt above
-  _ES_bootstrap "$@"
+  _esh_l $f && { shift; ${f/*.} "$@"; } || echo "ERROR loading $f"
 }
 export -f _ES_bootstrap
