continue

diff --git a/core/_esh_bootstrap b/core/_esh_bootstrap
--- a/core/_esh_bootstrap
+++ b/core/_esh_bootstrap
@@ -9,6 +9,10 @@ _esh_bootstrap() {
   f2=$(declare -f -- $f0)
   # compare before and after: if the same, then something went wrong in the
   # uploading/decryption/loading of the function
-  [ "$f1" = "$f2" ] && echo "escreen: failed to load $f" || $f0 "$@"
+  if [ "$f1" = "$f2" ]; then
+    echo "$FUNCNAME: failed to load $f" >&2
+    return 1
+  fi
+  $f0 "$@"
 }
 export -f _esh_bootstrap
