clean up vim init

diff --git a/core/_vime b/core/_vime
--- a/core/_vime
+++ b/core/_vime
@@ -4,18 +4,21 @@
 # calls _esh_i to init the session, to make sure the communication port is
 # functional
 _vime() {
-  local VIMRC=$ESH_TMP/$ESH_USER.vimrc
   set -e
-  _vimrc $VIMRC
-  export ESH_EDITOR=$ESH_TMP/$ESH_USER-vim
-  export FCEDIT=$ESH_EDITOR VISUAL=$ESH_EDITOR EDITOR=$ESH_EDITOR
-  [ ! -f $ESH_EDITOR -o -w $ESH_EDITOR ] && {
-    printf '#!/usr/bin/env bash\n%s\n_esh_i </dev/null\nexec vim -S %s "$@"' \
-      "$(declare -f _esh_e _esh_b _esh_l _esh_i)" \
-      $VIMRC \
-      > $ESH_EDITOR
-    chmod 755 $ESH_EDITOR || {
-      echo "ERROR: could not chmod $ESH_EDITOR: $?" >&2
+  local e=$ESH_TMP/$ESH_USER-vim
+  export ESH_EDITOR=$e FCEDIT=$e VISUAL=$e EDITOR=$e
+  [ ! -f $e -o -w $e ] && {
+    printf '#!/usr/bin/env bash
+%s
+_esh_i </dev/null
+export MYVIMRC=$(mktemp)
+_vimrc > $MYVIMRC
+export VIMINIT="source \$MYVIMRC|call delete(\$MYVIMRC)"
+exec vim "$@"' \
+      "$(declare -f _esh_e _esh_b _esh_l _esh_i _vimrc)" \
+      > $e
+    chmod 755 $e || {
+      echo "ERROR: could not chmod $e: $?" >&2
       return 1
     }
   }
