update

diff --git a/core/screen b/core/screen
--- a/core/screen
+++ b/core/screen
@@ -48,7 +48,10 @@ screen() {
               echo "$FUNCNAME: failed to register ESH_TERM_AUTH_TOKEN on STY=$pick_sty" >&2
               return 1
             fi
-            curl -v $ESH_ATSERVER_URL/refresh-auth-token
+            if ! curl -v -f -S $ESH_ATSERVER_URL/refresh-auth-token; then
+              echo "$FUNCNAME: failed call to /refresh-auth-token" >&2
+              return 1
+            fi
             #_esh_b registerSty $ESH_TERM_PID $pick_sty $root_sty
             # strip off "screen." prefix from $TERM to avoid "$TERM too long" issue
             env TERM=${TERM#screen.} screen -d -r $pick_sty
