Interim.

diff --git a/profile.lenio/vim b/profile.lenio/vim
--- a/profile.lenio/vim
+++ b/profile.lenio/vim
@@ -1,11 +1,11 @@
 # vim:filetype=sh
-function vim() {
-  export VIM_CLIPBOARD=$EXPECTSSH_TMPDIR/vim.clipboard.$USER
-  touch $VIM_CLIPBOARD
-  chmod 600 $VIM_CLIPBOARD || {
-    echo "WARNING: could not chmod on $VIM_CLIPBOARD!"
+vim() {
+  export VIM_CB=$ESH_TMP/$USER.vim.clipboard
+  touch $VIM_CB
+  chmod 600 $VIM_CB || {
+    echo "WARNING: could not chmod on $VIM_CB!"
     return
   }
-  export VIMINIT='map <c-v> :let @"=system("_esh_b GET_CB")<cr>:if col("$")-col(".")==1<bar>call feedkeys("p")<bar>else<bar>call feedkeys("P")<bar>endif<bar>redraw<bar>echon "Pasted " len(@") " characters"<cr>|vnoremap <C-c> y:call writefile(split(@","\n","b"),$VIM_CLIPBOARD)<cr>:!copy_to_clipboard $VIM_CLIPBOARD<cr>|colorscheme elflord|syntax enable|set noswapfile number hlsearch incsearch sw=2 ignorecase wrap nocompatible ruler ai showmatch modeline modelines=5 nobackup nowritebackup textwidth=0 expandtab formatoptions=croql wildignore=*.class path=.,,**|autocmd Filetype java setlocal omnifunc=javacomplete#Complete'
+  export VIMINIT='map <c-v> :let @"=system("_esh_b zGetCb")<cr>:if col("$")-col(".")==1<bar>call feedkeys("p")<bar>else<bar>call feedkeys("P")<bar>endif<bar>redraw<bar>echon "Pasted " len(@") " characters"<cr>|vnoremap <C-c> y:call writefile(split(@","\n","b"),$VIM_CB)<cr>:!cp2cb $VIM_CB<cr>|colorscheme elflord|syntax enable|set noswapfile number hlsearch incsearch sw=2 ignorecase wrap nocompatible ruler ai showmatch modeline modelines=5 nobackup nowritebackup textwidth=0 expandtab formatoptions=croql wildignore=*.class path=.,,**|autocmd Filetype java setlocal omnifunc=javacomplete#Complete'
   /usr/bin/vim "$@"
 }
